version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  signup:
    lang: golang-middleware
    handler: ./signup
    image: localhost:5001/signup:latest
  signin:
    lang: golang-middleware
    handler: ./signin
    image: localhost:5001/signin:latest
